### ISSUE TITLE
Sync data between KeyDB v6 - Redis v7

### ISSUE THREAD

**Issue by air3ijai** [leonchen83/redis-rdb-cli#38] opened 2022-12-29 17:32 UTC
**Describe the bug**
We just tried to Sync data from Redis v7 to the KeyDB v6, but looks like this is not supported.

**To Reproduce**
1. Run KeyDB v6
2. Run Redis v7 and add some data
3. Run the command
   ```
   rst -s redis://redis-v7:6379 -m redis://keydb-v6:6379
   ```
4. Application starting to process the data and finish to process the whole dataset
   ```
   \[483.3MB| 36.4MB/s]
   ```

 5. At the same time we see the following errors in the log
    ```
    2022-12-29 17:15:03,462 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB redis-ver: 7.0.5
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB redis-bits: 64
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB ctime: 1672334103
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB used-mem: 24348794648
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-stream-db: 0
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-id: 5a705558dc170011c96162558e3e21af9d3fecbc
    2022-12-29 17:15:03,463 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-offset: 4382
    2022-12-29 17:15:03,464 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB aof-base: 0
    2022-12-29 17:15:04,882 ERROR c.m.r.r.c.n.i.XEndpoint [sync-worker-4] ERR DUMP payload version or checksum are wrong
    2022-12-29 17:15:04,882 ERROR c.m.r.r.c.n.i.XEndpoint [sync-worker-1] ERR DUMP payload version or checksum are wrong
    2022-12-29 17:15:04,882 ERROR c.m.r.r.c.n.i.XEndpoint [sync-worker-3] ERR DUMP payload version or checksum are wrong
    ```
 6. Keyspace is empty on KeyDB v6.
    ```
    keydb-cli info keyspace
    # Keyspace
    ```

**Expected behavior**
We should be able to sync data from Redis v7 and KeyDB v6

**Version(run `rct --version` or `rct -V` and paste the information):**  
```
rct --version

redis rdb cli: v0.9.1 (1f96c81dd4935e2c7fc39f6bb227beede0c8ede4: 2022-05-01T08:10:04+0000)
home: /opt/redis-rdb-cli/bin/..
java version: 18.0.2-ea, vendor: Private Build
java home: /usr/lib/jvm/java-18-openjdk-amd64
default locale: en, platform encoding: UTF-8
os name: Linux, version: 5.11.20-300.fc34.x86_64, arch: amd64
```

**Additional context**
Probably the same things will happen with the Redis v6, because we were not able to restore RDB dump on v6 from v7 with the same massage as on KeyDB v6.
```
Can't handle RDB format version 10
```

Please see [[NEW] Support Redis 7 (RDB format version 10) dumps](https://github.com/Snapchat/KeyDB/issues/527)

**Comment by leonchen83** [comment] 2022-12-30 03:30
this tool support downgrade migration.
but you should change `conf` file to support this.
open  `/path/to/redis-rdb-cli/conf/redis-rdb-cli.conf` and edit `dump_rdb_version` from `-1` to `9`
after that run  `rst -s redis://redis-v7:6379 -m redis://keydb-v6:6379`

**Comment by air3ijai** [comment] 2023-01-03 17:24
Trying to continue migration but initialy just with the Redis v7/Redis v6. Just updated `redis-rdb-cli.conf`
```bash
grep dump_rdb_version=9 /opt/redis-rdb-cli/conf/redis-rdb-cli.conf
# Redis-6.2 : `dump_rdb_version=9`
# Redis-6.0.x : `dump_rdb_version=9`
# Redis-5.0.x : `dump_rdb_version=9`
dump_rdb_version=9
```

And get the following error with `rmt` and `rst`
```
/opt/redis-rdb-cli/bin/rmt -s 'redis://redis-7:6379?authPassword=password' -m redis://localhost:6379
\[    5 B|    0 B/s]
java.lang.ArrayIndexOutOfBoundsException: Index 26 out of bounds for length 26
	at com.moilioncircle.redis.replicator.util.ByteArray.set(ByteArray.java:74)
	at com.moilioncircle.redis.replicator.util.Lzf.encode(Lzf.java:356)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbEncoder.rdbSaveEncodedStringObject(BaseRdbEncoder.java:188)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbEncoder.rdbGenericSaveStringObject(BaseRdbEncoder.java:209)
	at com.moilioncircle.redis.replicator.rdb.dump.DumpRdbValueVisitor.applyHashListPack(DumpRdbValueVisitor.java:398)
	at com.moilioncircle.redis.rdb.cli.ext.rmt.AbstractRmtRdbVisitor.doApplyHashListPack(AbstractRmtRdbVisitor.java:169)
	at com.moilioncircle.redis.rdb.cli.ext.visitor.BaseRdbVisitor.applyHashListPack(BaseRdbVisitor.java:319)
	at com.moilioncircle.redis.replicator.rdb.RdbParser.parse(RdbParser.java:252)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$1.handle(RedisSocketReplicator.java:178)
	at com.moilioncircle.redis.replicator.cmd.ReplyParser.parse(ReplyParser.java:103)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.reply(RedisSocketReplicator.java:349)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.parseDump(RedisSocketReplicator.java:166)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.trySync(RedisSocketReplicator.java:142)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.open(RedisSocketReplicator.java:440)
	at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:49)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:123)
	at com.moilioncircle.redis.rdb.cli.ext.XRedisReplicator.open(XRedisReplicator.java:238)
	at com.moilioncircle.redis.rdb.cli.cmd.XRmt.call(XRmt.java:139)
	at com.moilioncircle.redis.rdb.cli.cmd.XRmt.call(XRmt.java:61)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.moilioncircle.redis.rdb.cli.Rmt.main(Rmt.java:28)
```

**log/redis-rdb-cli.log**
```
2023-01-03 17:20:20,242 INFO c.m.r.r.RedisSocketReplicator [main] Connected to redis-server[1.2.39.4:6379]
2023-01-03 17:20:20,247 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,247 INFO c.m.r.r.RedisSocketReplicator [main] PING
2023-01-03 17:20:20,247 INFO c.m.r.r.RedisSocketReplicator [main] PONG
2023-01-03 17:20:20,248 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF listening-port 44910
2023-01-03 17:20:20,248 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,248 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF ip-address 10.0.0.100
2023-01-03 17:20:20,249 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,249 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa eof
2023-01-03 17:20:20,249 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,249 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF capa psync2
2023-01-03 17:20:20,250 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,250 INFO c.m.r.r.RedisSocketReplicator [main] REPLCONF rdb-only 1
2023-01-03 17:20:20,250 INFO c.m.r.r.RedisSocketReplicator [main] OK
2023-01-03 17:20:20,250 INFO c.m.r.r.RedisSocketReplicator [main] PSYNC ? -1
2023-01-03 17:20:25,035 INFO c.m.r.r.RedisSocketReplicator [main] FULLRESYNC a24ae4325aba485f846b43c37fdc19ae03f6d4a5 42
2023-01-03 17:20:25,470 INFO c.m.r.r.RedisSocketReplicator [main] Disk-less replication.
2023-01-03 17:20:25,485 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB redis-ver: 7.0.7
2023-01-03 17:20:25,486 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB redis-bits: 64
2023-01-03 17:20:25,486 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB ctime: 1672766425
2023-01-03 17:20:25,486 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB used-mem: 24348366600
2023-01-03 17:20:25,486 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-stream-db: 0
2023-01-03 17:20:25,487 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-id: a24ae4325aba485f846b43c37fdc19ae03f6d4a5
2023-01-03 17:20:25,487 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB repl-offset: 42
2023-01-03 17:20:25,487 INFO c.m.r.r.r.DefaultRdbVisitor [main] RDB aof-base: 0
2023-01-03 17:20:25,684 INFO c.m.r.r.RedisSocketReplicator [main] socket closed. redis-server[1.2.3.4:6379]
```

Looks like something was migrated
```
# Keyspace
db0:keys=1475,expires=0,avg_ttl=0
```

**Comment by air3ijai** [comment] 2023-01-03 17:48
Another try following [your advise in case we have a big keys](39#issuecomment-1367707289)

**Convert RDB to AOF**
```bash
/opt/redis-rdb-cli/bin/rct -f resp -s /data/dump.rdb -o /data/dump.aof -r
/[ 20.4GB| 85.5MB/s]
```

**Import the data**
```
cat /data/dump.aof | redis-cli -h localhost -p 6379 --pipe

ERR Protocol error: invalid bulk length
```

**Comment by air3ijai** [comment] 2023-01-03 19:23
I also tried to use `rct` example - [Find top 50 largest keys](leonchen83/redis-rdb-cli#find-top-50-largest-keys)
```
/opt/redis-rdb-cli/bin/rct -f mem -s /data/dump.rdb -o /data/dump.mem -l 50
```
```
tail /data/dump.mem
0,module,"tree:13:2","43.3MB",module2,1,"43.3MB",""
0,module,"tree:10:2","40.2MB",module2,1,"40.2MB",""
0,module,"tree:7:2","35.4MB",module2,1,"35.4MB",""
0,module,"tree:6:3","25.6MB",module2,1,"25.6MB",""
0,module,"tree:12:3","25.6MB",module2,1,"25.6MB",""
0,module,"tree:14:5","25.6MB",module2,1,"25.6MB",""
0,module,"tree:5:2","25.6MB",module2,1,"25.6MB",""
0,module,"tree:17:7","25.6MB",module2,1,"25.6MB",""
0,module,"tree:15:4","25.6MB",module2,1,"25.6MB",""
0,module,"tree:16:4","25.6MB",module2,1,"25.6MB",""
```

So, there is nothing above the 512MB limit?

**Comment by leonchen83** [comment] 2023-01-04 02:25
hi
>>> /opt/redis-rdb-cli/bin/rct -f mem -s /data/dump.rdb -o /data/dump.mem -l 50
this file ordered by desc, try `head /data/dump.mem`

**Comment by leonchen83** [comment] 2023-01-04 04:17
> cat /data/dump.aof | redis-cli -h localhost -p 6379 --pipe

> ERR Protocol error: invalid bulk length

try `/path/to/redis-7.0.0/src/redis-check-aof /data/dump.aof`

you will see error like following
```
Start checking Old-Style AOF
0x              53: Expected \r\n, got: 7365
AOF analyzed: filename=./resp.aof, size=233, ok_up_to=52, ok_up_to_line=19, diff=181
AOF ./resp.aof is not valid. Use the --fix option to try fixing it.
```

The import info is `ok_up_to_line`. got that line number. for example `19`. and fetch related context of this line number(`sed -n '10, 30p' /data/dump.aof`). and paste to here. if it contains sensitive information. you could mail to chen.bao.yi@qq.com

**Comment by leonchen83** [comment] 2023-01-04 04:17
> cat /data/dump.aof | redis-cli -h localhost -p 6379 --pipe

> ERR Protocol error: invalid bulk length

try `/path/to/redis-7.0.0/src/redis-check-aof /data/dump.aof`

you will see error like following
```
Start checking Old-Style AOF
0x              53: Expected \r\n, got: 7365
AOF analyzed: filename=./resp.aof, size=233, ok_up_to=52, ok_up_to_line=19, diff=181
AOF ./resp.aof is not valid. Use the --fix option to try fixing it.
```

The import info is `ok_up_to_line`. got that line number. for example `19`. and fetch related context of this line number(`sed -n '10, 30p' /data/dump.aof`). and paste to here. if it contains sensitive information. you could mail to chen.bao.yi@qq.com

**Comment by leonchen83** [comment] 2023-01-04 04:40
about error 
```
java.lang.ArrayIndexOutOfBoundsException: Index 26 out of bounds for length 26
	at com.moilioncircle.redis.replicator.util.ByteArray.set(ByteArray.java:74)
	at com.moilioncircle.redis.replicator.util.Lzf.encode(Lzf.java:356)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbEncoder.rdbSaveEncodedStringObject(BaseRdbEncoder.java:188)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbEncoder.rdbGenericSaveStringObject(BaseRdbEncoder.java:209)
	at com.moilioncircle.redis.replicator.rdb.dump.DumpRdbValueVisitor.applyHashListPack(DumpRdbValueVisitor.java:398)
	at com.moilioncircle.redis.rdb.cli.ext.rmt.AbstractRmtRdbVisitor.doApplyHashListPack(AbstractRmtRdbVisitor.java:169)
```

It's a Lzf compress bug. will be fixed in version 0.9.2

**Comment by air3ijai** [comment] 2023-01-04 05:45
> this file ordered by desc, try head /data/dump.mem

Aha, now it is clearer
```
head dump.mem
database,type,key,size_in_bytes,encoding,num_elements,len_largest_element,expiry
0,module,"tree:20:1","792.1MB",module2,1,"792.1MB",""
0,module,"tree:22:1","792.1MB",module2,1,"792.1MB",""
0,module,"tree:21:1","792.1MB",module2,1,"792.1MB",""
0,module,"tree:15:1","484.9MB",module2,1,"484.9MB",""
0,module,"tree:19:1","484.9MB",module2,1,"484.9MB",""
0,module,"tree:18:1","484.9MB",module2,1,"484.9MB",""
0,module,"tree:16:1","484.9MB",module2,1,"484.9MB",""
0,module,"tree:17:1","484.9MB",module2,1,"484.9MB",""
0,module,"tree:14:1","480.1MB",module2,1,"480.1MB",""
```

This also is an answer to my question #39. During v7/v7 migration sometimes it was successfully, but we missed 3 keys and RBD size was ~ 3 GB smaller than  or the source.

**Comment by air3ijai** [comment] 2023-01-04 06:01
> try /path/to/redis-7.0.0/src/redis-check-aof /data/dump.aof

An AOF check - but on Redis v6, because this is where we import it
```bash
redis-check-aof /data/dump.aof
AOF analyzed: size=20629618644, ok_up_to=20629618644, diff=0
AOF is valid
```

So, looks good - let's try to import again
```bash
cat /data/dump.aof | redis-cli -h localhost -p 6379 --pipe
```
```
ERR Protocol error: invalid bulk length
```

**Comment by leonchen83** [comment] 2023-01-04 06:04
did you convert aof file contains these 3 big keys?
if yes, that can solve `invalid bulk length` question.
redis.conf by default bulk length is `proto-max-bulk-len 512mb`. you should change this value to `1024mb` on target redis.conf file

**Comment by air3ijai** [comment] 2023-01-04 06:29
**Config**
```
cat /etc/redis/redis.conf | grep proto-max-bulk-len

# proto-max-bulk-len 512mb
proto-max-bulk-len 1024mb
```

**Import**
```bash
cat /data/dump.aof | redis-cli -h localhost -p 6379 --pipe

All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 2995160
```

**Comparing**
```
# Redis v7
# Keyspace
db0:keys=1994658,expires=0,avg_ttl=0

# Redis v6
# Keyspace
db0:keys=1994658,expires=0,avg_ttl=0
```

Does comparison by the keys number can guarantee that all the data was migrated exactly and correctly, is there another way to check if we have same data on source and destination?

Will try to reproduce this with the KeyDB.

**Comment by leonchen83** [comment] 2023-01-04 06:37
you could sampling some different types of keys to compare whether they are consistent.
this tool can't do above. it should exactly and correctly if there is no bug.

**Comment by air3ijai** [comment] 2023-01-04 08:24
It also works fine on KeyDB v6 and there is a full guide how to perform that - [Migrate the data from Redis v7 to KeyDB v6 using redis-rdb-cli](https://github.com/leonchen83/redis-rdb-cli/issues/38)

And the following questions are remained
1. Is there a way to increase 512MB keys limit on redis-rdb-cli side?
    It will remove a necessity to use AOF

2. How to check the migrated data consistency?
    I will create a separate Feature request for that.

**Comment by leonchen83** [comment] 2023-01-05 02:28
I see the migration guide and well done.
> Create a RDB snapshot on Redis v7

> redis-cli -h localhost -p 6379 -a password \
> bgsave
> Copy RDB snapshot to the node with KeyDB v6

> scp ubuntu@keydb6:/data/dump.rdb /data

Actually redis-rdb-cli can backup remote rdb file to local by `rdt` command and do more than that like filter `db`, `type`, `key`

`rdt -b redis://host:port?authPassword=xxxx -o /data/dump.rdb`

**Comment by leonchen83** [comment] 2023-01-05 03:38
> 1. Is there a way to increase 512MB keys limit on redis-rdb-cli side?
> It will remove a necessity to use AOF

try `export JAVA_TOOL_OPTIONS=-Xms2g -Xmx2g`

**Comment by air3ijai** [comment] 2023-01-05 07:08
> try export JAVA_TOOL_OPTIONS=-Xms2g -Xmx2g

Will it work for the cases when we do have large keys, over 512MB? It is a question related to [your precedent comment](39#issuecomment-1367707289) about large keys.

**Comment by air3ijai** [comment] 2023-01-05 08:15
Did a test on Redis-7 to Redis-7 with a [large keys as shown above](#issuecomment-1370511373)
```bash
export JAVA_TOOL_OPTIONS="-Xms6g -Xmx6g"

rmt -s /data/dump.rdb -m redis://localhost:6379?authPassword=password

Picked up JAVA_TOOL_OPTIONS: -Xms6g -Xmx6g
\[ 20.5GB|102.8MB/s]
```

```
# Source
db0:keys=1994658,expires=0,avg_ttl=0

# Destination
db0:keys=1994655,expires=0,avg_ttl=0
```

So, big keys didn't migrate as it was already discussed. Is there a way to not skip them?

**Comment by leonchen83** [comment] 2023-01-05 08:16
hi. this is also need to change `proto bulk length to 1024mb` of target redis

**Comment by leonchen83** [comment] 2023-01-06 04:28
Hi
please help test [v0.9.2](https://github.com/leonchen83/redis-rdb-cli/releases/download/v0.9.2/redis-rdb-cli-release.zip)

**Comment by air3ijai** [comment] 2023-01-06 07:12
I did more that 10 test on Ubuntu 22.04 and Java 1.8, using `rmt` and `rct`
**Tests**
```
rmt -s redis://redis-6:6379 -m redis://redis-7:6379
rct -f mem -s redis://redis-7:6379 -o /data/dump.mem -l 50
```

**Environment**
```
redis-rdb-cli/bin/rmt --version
redis rdb cli: v0.9.2 (01d75ad66e6a021464b77b6a3b9a0724c3493253: 2023-01-06T04:21:51+0000)
home: /opt/redis-rdb-cli/bin/..
java version: 1.8.0_352, vendor: Private Build
java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
default locale: en, platform encoding: UTF-8
os name: Linux, version: 5.15.0-25-generic, arch: amd64
```


1. Data migrated successfully
2. Dump with big keys created successfully

All works fine, thank you for the quick fix - now migration is simpler :)

**Comment by air3ijai** [comment] 2023-01-06 07:13
A note about `rmt` with `-d` option

```
rmt -s redis://redis-7:6379 -m redis://localhost:6379 -d 1
/[ 20.2GB| 72.1MB/s]

real	4m41.562s
```

```
redis-cli info keyspace
# Keyspace
```

So, all is good - no data copied, because `db1` is empty - but why did we copied 20GB over the network?

**Comment by leonchen83** [comment] 2023-01-06 07:25
Hi
That because this tool rely redis replication protocol to migrate data to target.
But redis replication protocol does not support db filtering. so the only thing we can do is load and filter all rdb data to target.

**Comment by leonchen83** [comment] 2023-01-06 07:46
Hi
refer to [redis master slave sync infinite loop](https://stackoverflow.com/questions/39398956/redis-master-slave-sync-infinite-loop)
The root cause is `client-output-buffer-limit` is too small and this tool consume rdb event too slow.
so try `client-output-buffer-limit slave 0 0 0` but this change has risk. may crash redis master by OOM.

**Comment by air3ijai** [comment] 2023-01-06 08:02
1. Applied new limit
   ```
   redis-cli config set client-output-buffer-limit "slave 0 0 0"
   ```

2. Copied the data using `rst`

3. Returned limits back
   ```bash
   redis-cli config set client-output-buffer-limit "slave 268435456 67108864 60"
   ```

All works fine, thanks!

**Closed** 2023-01-08 04:06 UTC
Labels: bug
